version: '3'

services:

  app_challenge:
    build:
      context: ./node
    command: "node index.js"
    container_name: app_challenge
    entrypoint: dockerize -wait tcp://db_challenge:3306 -timeout 50s docker-entrypoint.sh
    networks:
      - codeedunet
    tty: true
    depends_on:
      - db_challenge

  nginx_challenge:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: robsonfs/nginx:prod
    container_name: nginx_challenge
    networks:
      - codeedunet
    ports:
      - "8080:80"
    depends_on:
      - app_challenge

  db_challenge:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_challenge
    restart: always
    tty: true
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - codeedunet

networks:
  codeedunet:
    driver: bridge
